version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: scores
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/application/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - mongo
  php-fpm:
    build: ./docker/php-fpm
    image: php-fpm
    ports:
      - 9000:9000
    volumes:
      - .:/application/